version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: NICU-db
    networks:
      - reservation-app
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 10s
      retries: 5

  migrator:
    build:
      context: .
      dockerfile: dbinit/Dockerfile.migrate
    networks:
      - reservation-app
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_URI: "mongodb://mongodb:27017/NICU-db?authSource=admin"  # Added authSource
      WAIT_HOSTS: mongodb:27017  # For health checking

  mongo_seed:
    image: mongo
    links:
      - mongodb
    volumes:
      - ./dbinit:/dbinit
    command:
      /dbinit/dbinit.sh
    networks:
      - reservation-app
    depends_on:
      - mongodb

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '5000:5000'
    networks:
      - reservation-app
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongodb:27017/NICU-db
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    networks:
      - reservation-app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

networks:
  reservation-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local